# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window_practice.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1244, 1087)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.myvideowidget = myVideoWidget(self.frame)
        self.myvideowidget.setObjectName("myvideowidget")
        self.verticalLayout.addWidget(self.myvideowidget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnStartAndPause = QtWidgets.QPushButton(self.frame)
        self.btnStartAndPause.setObjectName("btnStartAndPause")
        self.horizontalLayout_2.addWidget(self.btnStartAndPause)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.lblVolume = QtWidgets.QLabel(self.frame)
        self.lblVolume.setObjectName("lblVolume")
        self.horizontalLayout_2.addWidget(self.lblVolume)
        self.sliderVolume = mySlider(self.frame)
        self.sliderVolume.setProperty("value", 99)
        self.sliderVolume.setOrientation(QtCore.Qt.Horizontal)
        self.sliderVolume.setObjectName("sliderVolume")
        self.horizontalLayout_2.addWidget(self.sliderVolume)
        self.lblVolumeValue = QtWidgets.QLabel(self.frame)
        self.lblVolumeValue.setObjectName("lblVolumeValue")
        self.horizontalLayout_2.addWidget(self.lblVolumeValue)
        self.sliderTime = mySlider(self.frame)
        self.sliderTime.setMinimum(1)
        self.sliderTime.setMaximum(99)
        self.sliderTime.setSingleStep(1)
        self.sliderTime.setPageStep(10)
        self.sliderTime.setProperty("value", 2)
        self.sliderTime.setSliderPosition(2)
        self.sliderTime.setOrientation(QtCore.Qt.Horizontal)
        self.sliderTime.setObjectName("sliderTime")
        self.horizontalLayout_2.addWidget(self.sliderTime)
        self.lblTimeValue = QtWidgets.QLabel(self.frame)
        self.lblTimeValue.setText("")
        self.lblTimeValue.setObjectName("lblTimeValue")
        self.horizontalLayout_2.addWidget(self.lblTimeValue)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.setStretch(2, 1)
        self.horizontalLayout_2.setStretch(4, 1)
        self.horizontalLayout_2.setStretch(5, 9)
        self.horizontalLayout_2.setStretch(6, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout.setStretch(0, 9)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout_2.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1244, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menu.addAction(self.actionLoad)
        self.menu.addAction(self.actionExit)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnStartAndPause.setText(_translate("MainWindow", "开始"))
        self.lblVolume.setText(_translate("MainWindow", "音量"))
        self.lblVolumeValue.setText(_translate("MainWindow", "100%"))
        self.menu.setTitle(_translate("MainWindow", "菜单"))
        self.actionLoad.setText(_translate("MainWindow", "加载"))
        self.actionExit.setText(_translate("MainWindow", "退出"))
from mySlider import mySlider
from myVideoWidget import myVideoWidget
